postino.o: main.cpp connessione.cpp dijkstra.cpp EndPairingNO.cpp MatchingOttimo.cpp
	g++ -O3 -std=c++17 main.cpp connessione.cpp dijkstra.cpp EndPairingNO.cpp MatchingOttimo.cpp -I/usr/include/z3 -lz3

clean:
	rm -f *.o 